### ISSUE TITLE
Update README, ensure table code is working

### ISSUE THREAD

**Issue by sharlagelfand** [jhofman/datamations#37]
Once #23 is all closed out and we have a functional widget, will need to update the README illustrating how it works! I don't _think_ you can embed an htmlwidget into a static README so this may have to be in the form as htmlwidget -> movie -> GIF, but will double check on that.

Since we haven't done anything with the table code yet, will take a pass through and ensure it all still works and can be left in.

**Comment by sharlagelfand** [comment]
Need to update the README with the widget fot plotting, but confirming that the table code works and can be left in 👍

**Comment by sharlagelfand** [comment]
👍 plot examples in README work, all good:

```r
"small_salary %>% group_by(Degree) %>% summarize(mean = mean(Salary))" %>%
  datamation_sanddance()
```

https://user-images.githubusercontent.com/15895337/117343379-3abe8000-ae72-11eb-9ed9-99693850d85d.mov

```r
"small_salary %>% group_by(Degree, Work) %>% summarize(mean = mean(Salary))" %>%
  datamation_sanddance()
```

https://user-images.githubusercontent.com/15895337/117343541-65a8d400-ae72-11eb-8be0-54d113b6e8a2.mov

Some notes on discrepancies that remain between the originals (in the main branch README) and these versions, + beyond in the case of 3 grouping variables (e.g. penguins) and some general thoughts on what else we might want to fix. making a checklist so i can mark off as we add these in:

- [ ] axes (+ titles) are missing (discussed in #39)
- [ ] y-axis should be autoscaled to range of data, instead of from 0 (discussed in #23)
- [ ] values not centred on the x-axis, e.g. some appear on the edge of their facets instead of centred (discussed in #32) - maybe just domain needs to be increased to show 
- [ ] x-axis values are numeric, not actual group labels in the case of 3+ variables (discussed in #33) - wondering if it'll work to have numeric values as the breaks, but the values (e.g. undefined, male, female) as the labels. similar to what i discussed/figured out [here](https://github.com/jhofman/datamations/issues/25#issuecomment-824344862) + beyond in that thread, but with sex instead of the islands on the x-axes.
- [ ] Maybe we should add facet titles? so "Degree" as the title on the column facets and "Work" as the title on the row ones
- [ ] Filled points instead of transparent? Seems pretty quick to change in [vega lite](https://vega.github.io/vega-lite/docs/point.html#scatter-plot) and much more like the scatter plots I'm used to :) I can update in the specs I'm passing but likely needs to be updated on the JS side as well
- [ ] Mostly just curious on this end... what's going on with the size of the facet labels changing? Goes smaller -> bigger -> smaller a few times

might have missed some things but will add to this as I find em! cc @jhofman @giorgi-ghviniashvili

**Comment by jhofman** [comment]
awesome, this looks great and thanks for summarizing the needed updates in an easy-to-follow checklist!

**Comment by giorgi-ghviniashvili** [comment]
> Filled points instead of transparent? Seems pretty quick to change in vega lite and much more like the scatter plots I'm used to :) I can update in the specs I'm passing but likely needs to be updated on the JS side as well

yes, try to use `filled: true`.

**Comment by giorgi-ghviniashvili** [comment]
>  x-axis values are numeric, not actual group labels in the case of 3+ variables (discussed in #33) - wondering if it'll work to have numeric values as the breaks, but the values (e.g. undefined, male, female) as the labels. similar to what i discussed/figured out here + beyond in that thread, but with sex instead of the islands on the x-axes.

@sharlagelfand  Since this is encoding.x.axis , can you try to set it yourself and just sent it via spec? Use `tickExpr`.

**Comment by giorgi-ghviniashvili** [comment]
> values not centred on the x-axis, e.g. some appear on the edge of their facets instead of centred (discussed in #32) - maybe just domain needs to be increased to show

Please try to add 0.5 for padding.

**Comment by sharlagelfand** [comment]
Sorry, just finally gone through all these now!

> > Mostly just curious on this end... what's going on with the size of the facet labels changing? Goes smaller -> bigger -> smaller a few times
> 
> @sharlagelfand please update gemini.web.js with [this](https://github.com/uwdata/gemini/blob/master/gemini.web.js) to include latest `tickPadding` fix.

Will try that - you don't have the latest version [here](https://raw.githack.com/jhofman/datamations/gio/generalization/sandbox/app/index.html) right? The sizes are still changing there



> > Filled points instead of transparent? Seems pretty quick to change in vega lite and much more like the scatter plots I'm used to :) I can update in the specs I'm passing but likely needs to be updated on the JS side as well
> 
> yes, try to use `filled: true`.

The specs [here](https://github.com/jhofman/datamations/tree/refactor-test/sandbox/specs-for-infogrid) now all use `filled: true` but it doesn't perpetuate through the datamation [here](https://raw.githack.com/jhofman/datamations/gio/generalization/sandbox/app/index.html), maybe needs to be updated in the JS too?

> > Maybe we should add facet titles? so "Degree" as the title on the column facets and "Work" as the title on the row ones
> 
> You can add titles now, currently `facet.row.title` and `facet.column.title` are null.

Have updated the `title`s in the specs [here](https://github.com/jhofman/datamations/tree/refactor-test/sandbox/specs-for-infogrid) but doesn't look like they're coming up

> > x-axis values are numeric, not actual group labels in the case of 3+ variables (discussed in #33) - wondering if it'll work to have numeric values as the breaks, but the values (e.g. undefined, male, female) as the labels. similar to what i discussed/figured out here + beyond in that thread, but with sex instead of the islands on the x-axes.
> 
> @sharlagelfand Since this is encoding.x.axis , can you try to set it yourself and just sent it via spec? Use `tickExpr`.

Will try this on my end - I figured it out before so shouldn't be too bad to do again.



> > values not centred on the x-axis, e.g. some appear on the edge of their facets instead of centred (discussed in #32) - maybe just domain needs to be increased to show
> 
> Please try to add 0.5 for padding.

Where should I add this? To the actual X values? Or padding the domain on the plot?

**Comment by jhofman** [comment]
@sharlagelfand, @giorgi-ghviniashvili: just checking in on this. is it realistic to try to update the README w/ the new examples today (before tonight's talk)? 

it's okay if not, but just want to get a sense.

**Comment by sharlagelfand** [comment]
@jhofman definitely realistic and my plan to! If @giorgi-ghviniashvili has time to answer some of the questions in my comment above we can make some progress on the more visual aspects of the datamations, but if not will definitely update with how it's looking now. The [app](https://sharlagelfand.shinyapps.io/datamations/) is updated with the latest versions of everything.

Would you be able to merge the two existing PRs, then I can rebase on them, update the README and PR my `refactor-test` branch? Then if we are able to make additional changes before tonight I can do that on a new, smaller branch so we don't have to worry about this mammoth branch too late in the day 😁

**Comment by jhofman** [comment]
great!

btw, just tried out the app and saw some funniness in placement of the points on the last frame:

![Screen Shot 2021-05-10 at 12 30 40 PM](https://user-images.githubusercontent.com/79563/117693008-926b2d00-b18b-11eb-9e84-cfa0bb32d90f.png)

**Comment by giorgi-ghviniashvili** [comment]
> Where should I add this? To the actual X values? Or padding the domain on the plot?

`axis.scale.domain`

- filled: true fixed
- facet titles fixed

**Comment by giorgi-ghviniashvili** [comment]
@jhofman  Ok, I fixed it. The problem was that distances between facet title and axis and regular axis title and axis are different, which made the top positions different. 
Actually generally these kind of things are cons of "hacking facets", we need to have some hardcoded padding / spacing adjustments..

**Comment by sharlagelfand** [comment]
Thanks @giorgi-ghviniashvili! Filled points and facet title are working now.

**Comment by sharlagelfand** [comment]
Looks like something is going on here with the scaling of the y-axis - it's scaled just to the domain for the jitter view (which has no axes, as shown in [this comment](https://github.com/jhofman/datamations/issues/39#issuecomment-834738815)) but then scaled 0 -> full domain for the summary view (which has axes). 
The consequence is that briefly it shows the axis for the jitter view but with *wrong* values, so it looks like somehow values between 0 and 40 (Masters in Academia) have a mean of ~85, which of course isn't what's actually happening in the data

So the animation has these frames:

### jitter view, no axes

<img width="712" alt="Screen Shot 2021-05-10 at 3 48 17 PM" src="https://user-images.githubusercontent.com/15895337/117716230-580f8900-b1a7-11eb-8315-a6a535cf07f8.png">

### jitter view, incorrect axes

<img width="831" alt="Screen Shot 2021-05-10 at 3 49 00 PM" src="https://user-images.githubusercontent.com/15895337/117716283-68276880-b1a7-11eb-96c8-0be4948cc4f8.png">

### summary view, correct axes (but domain is too large)

<img width="796" alt="Screen Shot 2021-05-10 at 3 49 07 PM" src="https://user-images.githubusercontent.com/15895337/117716253-5e056a00-b1a7-11eb-88b0-edec68cde57b.png">

**Comment by sharlagelfand** [comment]
(Will also close this issue and move outstanding stuff to new issues tomorrow, since the README _is_ updated!)

**Comment by jhofman** [comment]
thanks @sharlagelfand 

@giorgi-ghviniashvili is it possible that there's still a bug in the axis positioning or labeling? seems like the averages in the last frame are in the 90k region, but i remember them being in the high 80s.

**Comment by giorgi-ghviniashvili** [comment]
@jhofman no, the y values are 90s:
![image](https://user-images.githubusercontent.com/6615532/118007935-ac5c6980-b35d-11eb-9324-237eb19a527c.png)

**Comment by sharlagelfand** [comment]
Looks like these are right:

<img width="589" alt="Screen Shot 2021-05-14 at 11 46 50 AM" src="https://user-images.githubusercontent.com/15895337/118296181-aaec8780-b4aa-11eb-9e79-6368f4a01769.png">

```
  Degree   mean
1 Masters  90.2
2 PhD      88.2
```

so going to close this now!

**Comment by jhofman** [comment]
Looks like the [shiny app](https://sharlagelfand.shinyapps.io/datamations/) still shows two values about 90. is that [previous screenshot](https://github.com/jhofman/datamations/issues/37#issuecomment-841330406) from the app or somewhere else?

![Screen Shot 2021-05-17 at 10 31 08 AM](https://user-images.githubusercontent.com/79563/118506250-280e3b80-b6fb-11eb-9381-17b6569c10fe.png)

**Comment by sharlagelfand** [comment]
Huh, you're right! And the data shown in the app is wrong too (but seems to match the values on the plot)

<img width="1270" alt="Screen Shot 2021-05-17 at 10 36 32 AM" src="https://user-images.githubusercontent.com/15895337/118507093-ea5de280-b6fb-11eb-87ba-ee7e9ad3fc5e.png">

Not sure what's going on here - I'll dig into it.

**Comment by sharlagelfand** [comment]
Oooh - there's two different "small salary" data sets - `small_salary` and `small_salary_data`:

``` r
library(dplyr)
library(datamations)

small_salary
#> # A tibble: 100 x 6
#>       ID Degree  Work     Salary i     order
#>    <int> <fct>   <fct>     <dbl> <chr> <int>
#>  1    22 Masters Academia   81.9 id        1
#>  2    96 PhD     Academia   84.5 id        2
#>  3    10 Masters Academia   82.9 id        3
#>  4    42 PhD     Academia   83.8 id        4
#>  5    55 PhD     Academia   83.8 id        5
#>  6    14 PhD     Academia   85.3 id        6
#>  7    33 PhD     Industry   91.4 id        7
#>  8   100 PhD     Academia   85.3 id        8
#>  9    57 Masters Academia   83.3 id        9
#> 10     2 PhD     Industry   92.3 id       10
#> # … with 90 more rows

small_salary %>% 
  group_by(Degree) %>%
  summarise(mean = mean(Salary))
#> # A tibble: 2 x 2
#>   Degree   mean
#>   <fct>   <dbl>
#> 1 Masters  90.2
#> 2 PhD      88.2

small_salary_data
#> # A tibble: 30 x 3
#>    Degree  Work     Salary
#>    <chr>   <chr>     <dbl>
#>  1 Masters Industry     86
#>  2 Masters Academia     71
#>  3 PhD     Industry    104
#>  4 Masters Industry     94
#>  5 Masters Academia     93
#>  6 Masters Academia     96
#>  7 PhD     Academia    100
#>  8 Masters Industry     86
#>  9 PhD     Academia     80
#> 10 Masters Industry     85
#> # … with 20 more rows

small_salary_data %>%
  group_by(Degree) %>% 
  summarise(mean = mean(Salary))
#> # A tibble: 2 x 2
#>   Degree   mean
#>   <chr>   <dbl>
#> 1 Masters  90.6
#> 2 PhD      92.1
```

Will open a new issue for this.
